export const products = [
    {
        id: 1,
        name: 'Saphed Dhokla Aata',
        username: 'RamDev Baba Gruhudyog',
        url: 'https://5.imimg.com/data5/ANDROID/Default/2020/9/LF/GN/CJ/98908646/img-20200801-wa0588-jpg-500x500.jpg',
        Prize: 'Rs. 60',
        email: 'ramdev@gmail.com',
    },
    {
        id: 3,
        name: 'Masaledar Papad',
        username: 'Mahavir Papad Gruh Udyog',
        url: 'https://lh5.googleusercontent.com/p/AF1QipOGWWnoiyANgqOOnPVnrMBksVdvSUcghGrc5byu=w1440-h1080-k-no',
        Prize: 'Rs. 20',
        email: 'mahaveerpgu@gmail.com',
    },
    {
        id: 4,
        name: 'Aanand Moong Papad',
        username: 'Aanand Gruh Udyog',
        url: 'https://5.imimg.com/data5/LT/CH/MY-39771328/anand-moong-papad-500x500.jpg',
        Prize: 'Rs. 80',
        email: 'aanandgu@gmail.com',
    },
    {
        id: 5,
        name: 'Masala Roll',
        username: 'Ganesh Gruh Udyog',
        url: 'https://ganeshgruhudyog.com/wp-content/uploads/2022/09/76018-1600166834324.jpg',
        Prize: 'Rs. 170',
        email: 'ganeshgu@gmail.com',
    },
    {
        id: 6,
        name: 'Khandeshi Masala',
        username: 'Sadhan Gruh Udyog',
        url: 'https://gruhudyog.in/Cpanel/Upload/ProductLargeImages/5f278d92__Khandeshi%20Masala%20Front%20Side.jpg',
        Prize: 'Rs. 210',
        email: 'sadhanagu@gmail.com',
    },
    {
        id: 7,
        name: 'Nirolle Rivah Rifined vegetable oil',
        username: 'Vegetable - Tamanna Gruh Udyog',
        url: 'https://nirolee.com/wp-content/uploads/2022/05/oil-pouch-2-min-1-2048x2048.png',
        Prize: 'Rs. 270',
        email: 'nirollevtgu@gmail.com',
    },
    {
        id: 8,
        name: 'Special Kanda Lasun Masala',
        username: 'Nandai Mata Mahila Gruh Udyog',
        url: 'https://gruhudyog.in/Cpanel/Upload/ProductLargeImages/5f278d92__Khandeshi%20Masala%20Front%20Side.jpg',
        Prize: 'Rs. 380',
        email: 'Nandaimatamgu@gmail.com',
    },
    {
        id: 9,
        name: 'Gulab Jamun',
        username: 'Shree Gruh Udyog',
        url: 'https://cpimg.tistatic.com/07429986/b/4/200-gm-Gulab-Jamun-Instant-Ready-Mix.jpg',
        Prize: 'Rs. 430',
        email: 'shregu@gmail.com',
    },
    {
        id: 10,
        name: 'Diwali Faral',
        username: 'Vaishnavi Gruh Udyog - Food manufacturing supply',
        url: 'https://lh5.googleusercontent.com/p/AF1QipMEQoo4K3HgI3D9AQiIaA75HW6QDlpqXajfr9HP',
        Prize: 'Rs. 50',
        email: 'vaishnavigufoodms@gmail.com',
    },
    {
        id: 11,
        name: 'Diwali Faral',
        username: 'Khare Gruh Udyog Pen - Food Manufacturer',
        url: 'https://tiimg.tistatic.com/fp/1/005/985/tikha-gathiya-844.jpg',
        Prize: 'Rs. 50',
        email: 'kharegupenfm@gmail.com',
    },
    {
        id: 12,
        name: 'Tasty and Authentic Indian Til Chutney',
        username: 'Arvi Gruh Udyog',
        url: 'https://m.media-amazon.com/images/I/41GCLnqjb7L.jpg',
        Prize: 'Rs. 60',
        email: 'arvigu@gmail.com',
    },
    {
        id: 13,
        name: 'Rice Chakri',
        username: 'Ganesh Gruh Udyog',
        url: 'https://d3eiv471cwo366.cloudfront.net/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/r/i/rice_chakri.jpg',
        Prize: 'Rs. 80',
        email: 'ganeshgu@gmail.com',
    },
    {
        id: 14,
        name: 'Pudina Kurkure',
        username: 'Ganesh Gruh Udyog',
        url: 'https://d3eiv471cwo366.cloudfront.net/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/p/u/pudina_kurkure.jpg',
        Prize: 'Rs. 90',
        email: 'ganeshgu@gmail.com',
    },
    {
        id: 15,
        name: 'Res Chilly Gavean Chuteny',
        username: 'Shreya Gavran Tadka',
        url: 'https://5.imimg.com/data5/ANDROID/Default/2020/9/LF/GN/CJ/98908646/img-20200801-wa0588-jpg-500x500.jpg',
        Prize: 'Rs. 10',
        email: 'shreyagt@gmail.com',
    },
    {
        id: 16,
        name: 'Varan Bhat',
        username: 'Sakhi Gruh Udyog',
        url: 'https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/lxt4qhnrrwt65jp9o2ui',
        Prize: 'Rs. 90',
        email: 'sakhigu@gmail.com',
    },
];


